<script setup lang="ts">
import {ref,onMounted} from 'vue';import {hoursToSeconds} from '../lib/interval';import {api,errorText} from '../lib/api';import type {Configuration,Service} from '../types';import Icon from '../components/Icon.vue';import Notice from '../components/Notice.vue';import Modal from '../components/Modal.vue'
const intervalHours=ref<number|string>(6)
const config=ref<Configuration>(),form=ref<Service>(),loading=ref(false),busy=ref(false),error=ref(''),success=ref(''),confirmOpen=ref(false),confirmText=ref('')
async function load(){loading.value=true;error.value='';try{config.value=await api<Configuration>('/api/admin/config');form.value={...config.value.service};intervalHours.value=config.value.service.interval_seconds/3600}catch(e){error.value=errorText(e)}finally{loading.value=false}}
onMounted(load)
function validInterval(){try{hoursToSeconds(intervalHours.value);return true}catch(e){error.value=errorText(e);success.value='';return false}}
function submit(){if(!form.value||!validInterval())return;if(!form.value.dry_run){confirmText.value='';confirmOpen.value=true}else void save()}
async function save(){if(!config.value||!form.value||!validInterval())return;busy.value=true;error.value='';success.value='';try{const service={source_url:form.value.source_url,interval_seconds:hoursToSeconds(intervalHours.value),timeout_seconds:form.value.timeout_seconds,attempts:form.value.attempts,dry_run:form.value.dry_run,max_ips:form.value.max_ips};config.value=await api<Configuration>('/api/admin/config',{method:'PATCH',body:{revision:config.value.revision,service,...(!form.value.dry_run?{confirm_apply:true}:{})}});form.value={...config.value.service};intervalHours.value=config.value.service.interval_seconds/3600;confirmOpen.value=false;success.value='设置已保存并生效。'}catch(e){error.value=errorText(e)}finally{busy.value=false}}
</script><template><div class="admin-heading"><div><span class="eyebrow">SERVICE SETTINGS</span><h1>服务设置</h1><p>配置优选来源与任务调度。</p></div><button class="btn" :disabled="loading||busy" @click="load"><Icon name="refresh" :size="17"/>重新加载</button></div><Notice :message="error"/><Notice :message="success" kind="success"/><form v-if="form" @submit.prevent="submit"><section class="card settings-section"><div class="card-heading"><h2>优选 IP 来源</h2><p class="muted">直接读取现有接口，不执行测速。</p></div><label class="field">优选来源<select v-model="form.source_url" @change="form.dry_run=true"><option value="https://ip.164746.xyz/ipTop.html">ip.164746.xyz · 原有来源</option><option value="https://ip.v2too.top/api/nodes">ip.v2too.top · 三网首选 IP</option><option v-if="config && !['https://ip.164746.xyz/ipTop.html','https://ip.v2too.top/api/nodes'].includes(config.service.source_url)" :value="config.service.source_url">服务器配置来源</option></select></label><div class="form-grid"><label class="field">最大 IP 数量<input v-model.number="form.max_ips" type="number" min="1" max="1000" required><span class="help">超限、空内容和非法 IP 会被拒绝。</span></label><label class="field">请求超时（秒）<input v-model.number="form.timeout_seconds" type="number" min="1" max="60" required></label></div></section><section class="card settings-section"><div class="card-heading"><h2>任务调度</h2><p class="muted">修改配置后无需重启服务。</p></div><div class="form-grid"><label class="field">运行间隔（h）<input v-model="intervalHours" type="number" :min="30/3600" :max="604800/3600" step="any" required><span class="help">默认 6 h；支持小数，须对应整数秒。两次任务之间至少等待 30 秒，最多 168 h。</span></label><label class="field">读取重试次数<input v-model.number="form.attempts" type="number" min="1" max="5" required><span class="help">写请求不会自动重发。</span></label></div><label class="field">运行模式<select v-model="form.dry_run"><option :value="true">预览模式 · 不修改 DNS</option><option :value="false">正式同步 · 按周期更新 DNS</option></select></label><div :class="['notice',form.dry_run?'info':'warning']"><Icon :name="form.dry_run?'lock':'shield'" :size="18"/>{{form.dry_run?'只获取地址、读取现有解析和生成更新计划。':'正式模式会修改已有 A 记录；启用前请核对目标。'}}</div></section><div class="button-row wrap settings-save"><button class="btn primary" :disabled="busy"><Icon name="check" :size="18"/>{{busy?'保存中…':'保存设置'}}</button><span class="help">并发修改会被拒绝，请重新加载后再提交。</span></div></form><div v-else class="card loading-state">{{loading?'正在加载配置…':'配置暂不可用，请重试。'}}</div><Modal :open="confirmOpen" title="启用正式同步" :busy="busy" @close="confirmOpen=false"><p>保存后，后台计划任务可能立即开始更新 {{config?.targets.length||0}} 个 DNS 目标。多条修改不是事务，不会自动回滚。</p><div class="notice warning">请先完成一次预览。</div><label class="field">输入“启用同步”确认<input v-model="confirmText" autocomplete="off" placeholder="启用同步"></label><Notice :message="error"/><div class="modal-actions"><button class="btn" :disabled="busy" @click="confirmOpen=false">取消</button><button class="btn primary" :disabled="busy||confirmText!=='启用同步'" @click="save">确认启用</button></div></Modal></template>
